- name: Check existence of container
  command: podman container exists thelounge
  register: container_exists
  failed_when: container_exists.rc > 1

- name: Create container
  command: >
    podman create --name=thelounge
    -p 9000:9000
    -v thelounge:/var/opt/thelounge
    thelounge/thelounge
  when: container_exists.rc == 1

- name: Configure firewalld
  firewalld:
    port: '{{ item }}'
    state: enabled
    immediate: true
    permanent: true
  loop:
    - 9000/tcp
  become: true
  when: container_exists.rc == 1

- name: Install systemd service
  copy:
    src: thelounge.service
    dest: '{{ configdir }}/systemd/user/thelounge.service'
    mode: 0644

- name: Enable systemd service
  systemd:
    name: thelounge.service
    scope: user
    state: started
    enabled: true
